// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdateAndRestart(arg1:string):Promise<void>;

export function CheckUpdate():Promise<main.VersionInfo | null>;

export function GetAgentConfig():Promise<main.AgentConfig>;

export function GetPrinterConfig():Promise<Record<string, any>>;

export function GetPrintersList():Promise<Array<string>>;

export function GetSelectedPrinter():Promise<string>;

export function GetStatus():Promise<string>;

export function IsConfigured():Promise<boolean>;

export function MinimizeToTray():Promise<void>;

export function QuitApp():Promise<void>;

export function Reconnect():Promise<void>;

export function SaveAgentConfig(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetSelectedPrinter(arg1:string,arg2:string):Promise<void>;

export function ShouldQuit():Promise<boolean>;

export function ShowWindow():Promise<void>;
