// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdateAndRestart(arg1:string):Promise<void>;

export function CheckUpdate():Promise<main.VersionInfo>;

export function ClearHotFolder():Promise<void>;

export function Disconnect():Promise<void>;

export function GetAgentConfig():Promise<main.AgentConfig>;

export function GetAutoStartEnabled():Promise<boolean>;

export function GetPrintSettings():Promise<Record<string, any>>;

export function GetPrinterConfig():Promise<Record<string, any>>;

export function GetPrinterPaperSizes(arg1:string):Promise<Array<{name:string;kind:number;width:number;height:number}>>;

export function GetPrintersList():Promise<Array<string>>;

export function GetSelectedPrinter():Promise<string>;

export function GetStatus():Promise<string>;

export function GetVersion():Promise<string>;

export function IsConfigured():Promise<boolean>;

export function ListSavedArts():Promise<Array<main.SavedArtInfo>>;

export function MinimizeToTray():Promise<void>;

export function OpenHotFolder():Promise<void>;

export function QuitApp():Promise<void>;

export function Reconnect():Promise<void>;

export function SaveAgentConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetAutoStartEnabled(arg1:boolean):Promise<void>;

export function SetSelectedPrinter(arg1:string,arg2:string):Promise<void>;

export function ShouldQuit():Promise<boolean>;

export function ShowWindow():Promise<void>;
