// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdateAndRestart(arg1) {
  return window['go']['main']['App']['ApplyUpdateAndRestart'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearHotFolder() {
  return window['go']['main']['App']['ClearHotFolder']();
}

export function GetAgentConfig() {
  return window['go']['main']['App']['GetAgentConfig']();
}

export function GetAutoStartEnabled() {
  return window['go']['main']['App']['GetAutoStartEnabled']();
}

export function GetPrinterConfig() {
  return window['go']['main']['App']['GetPrinterConfig']();
}

export function GetPrintersList() {
  return window['go']['main']['App']['GetPrintersList']();
}

export function GetSelectedPrinter() {
  return window['go']['main']['App']['GetSelectedPrinter']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsConfigured() {
  return window['go']['main']['App']['IsConfigured']();
}

export function ListSavedArts() {
  return window['go']['main']['App']['ListSavedArts']();
}

export function MinimizeToTray() {
  return window['go']['main']['App']['MinimizeToTray']();
}

export function OpenHotFolder() {
  return window['go']['main']['App']['OpenHotFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SaveAgentConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveAgentConfig'](arg1, arg2, arg3, arg4);
}

export function SetAutoStartEnabled(arg1) {
  return window['go']['main']['App']['SetAutoStartEnabled'](arg1);
}

export function SetSelectedPrinter(arg1, arg2) {
  return window['go']['main']['App']['SetSelectedPrinter'](arg1, arg2);
}

export function ShouldQuit() {
  return window['go']['main']['App']['ShouldQuit']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
